spring:
  data:
    neo4j:
      uri: http://recommendation-neo4j:7474
server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true