spring:
  application:
    name: moviesui
  profiles:
    active: development
server:
  port: 9006
---
spring:
  profiles: development
  data:
    neo4j:
      uri: http://movies-ui-neo4j:7474
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/